### ISSUE TITLE
'"Not found"

### ISSUE THREAD

**Issue by tomByrer** [signalnerve/workers-graphql-server#7]
![cfw-gql-not-found](https://user-images.githubusercontent.com/1308419/62999342-c2a95e80-be33-11e9-9c59-e6b148cace88.PNG)

**Comment by signalnerve** [comment]
Hey @tomByrer, was this the link in the repo description? I've updated it, should be https://workers-graphql.signalnerve.workers.dev/___graphql now

**Comment by signalnerve** [comment]
Closing this, let me know if I've misunderstood where the bad link was!
